# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1249, 830)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.ID_label = QLabel(self.centralwidget)
        self.ID_label.setObjectName(u"ID_label")
        self.ID_label.setGeometry(QRect(350, 60, 41, 41))
        self.ID_label.setStyleSheet(u"font: 28pt \"Segoe UI\";\n"
"font: 22pt \"Segoe UI\";")
        self.ID_textInput = QTextEdit(self.centralwidget)
        self.ID_textInput.setObjectName(u"ID_textInput")
        self.ID_textInput.setGeometry(QRect(400, 60, 141, 41))
        self.ConnectButton = QPushButton(self.centralwidget)
        self.ConnectButton.setObjectName(u"ConnectButton")
        self.ConnectButton.setGeometry(QRect(590, 60, 121, 41))
        self.ConnectButton.setStyleSheet(u"font: 20pt \"Segoe UI\";")
        self.DisconnectButton = QPushButton(self.centralwidget)
        self.DisconnectButton.setObjectName(u"DisconnectButton")
        self.DisconnectButton.setGeometry(QRect(730, 60, 151, 41))
        self.DisconnectButton.setStyleSheet(u"font: 20pt \"Segoe UI\";")
        self.Details_label = QLabel(self.centralwidget)
        self.Details_label.setObjectName(u"Details_label")
        self.Details_label.setGeometry(QRect(300, 120, 91, 41))
        self.Details_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Details_textInput = QTextEdit(self.centralwidget)
        self.Details_textInput.setObjectName(u"Details_textInput")
        self.Details_textInput.setGeometry(QRect(400, 120, 481, 41))
        self.State_label = QLabel(self.centralwidget)
        self.State_label.setObjectName(u"State_label")
        self.State_label.setGeometry(QRect(320, 170, 71, 41))
        self.State_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.State_textInput = QTextEdit(self.centralwidget)
        self.State_textInput.setObjectName(u"State_textInput")
        self.State_textInput.setGeometry(QRect(400, 170, 481, 41))
        self.Timestamp_label = QLabel(self.centralwidget)
        self.Timestamp_label.setObjectName(u"Timestamp_label")
        self.Timestamp_label.setGeometry(QRect(180, 260, 131, 41))
        self.Timestamp_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Largeimage_label = QLabel(self.centralwidget)
        self.Largeimage_label.setObjectName(u"Largeimage_label")
        self.Largeimage_label.setGeometry(QRect(330, 350, 161, 41))
        self.Largeimage_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Smallimage_label = QLabel(self.centralwidget)
        self.Smallimage_label.setObjectName(u"Smallimage_label")
        self.Smallimage_label.setGeometry(QRect(700, 350, 161, 41))
        self.Smallimage_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Keylarge_label = QLabel(self.centralwidget)
        self.Keylarge_label.setObjectName(u"Keylarge_label")
        self.Keylarge_label.setGeometry(QRect(260, 400, 51, 41))
        self.Keylarge_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Keysmall_label = QLabel(self.centralwidget)
        self.Keysmall_label.setObjectName(u"Keysmall_label")
        self.Keysmall_label.setGeometry(QRect(630, 400, 51, 41))
        self.Keysmall_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.keylarge_input = QTextEdit(self.centralwidget)
        self.keylarge_input.setObjectName(u"keylarge_input")
        self.keylarge_input.setGeometry(QRect(320, 400, 271, 41))
        self.keysmall_input = QTextEdit(self.centralwidget)
        self.keysmall_input.setObjectName(u"keysmall_input")
        self.keysmall_input.setGeometry(QRect(690, 400, 271, 41))
        self.Textlarge_label = QLabel(self.centralwidget)
        self.Textlarge_label.setObjectName(u"Textlarge_label")
        self.Textlarge_label.setGeometry(QRect(250, 460, 61, 41))
        self.Textlarge_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Textlarge_input = QTextEdit(self.centralwidget)
        self.Textlarge_input.setObjectName(u"Textlarge_input")
        self.Textlarge_input.setGeometry(QRect(320, 460, 271, 41))
        self.Textsmall_label = QLabel(self.centralwidget)
        self.Textsmall_label.setObjectName(u"Textsmall_label")
        self.Textsmall_label.setGeometry(QRect(620, 460, 61, 41))
        self.Textsmall_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Textsmall_input = QTextEdit(self.centralwidget)
        self.Textsmall_input.setObjectName(u"Textsmall_input")
        self.Textsmall_input.setGeometry(QRect(690, 460, 271, 41))
        self.Buttonone_label = QLabel(self.centralwidget)
        self.Buttonone_label.setObjectName(u"Buttonone_label")
        self.Buttonone_label.setGeometry(QRect(330, 520, 111, 41))
        self.Buttonone_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Buttontwo_label = QLabel(self.centralwidget)
        self.Buttontwo_label.setObjectName(u"Buttontwo_label")
        self.Buttontwo_label.setGeometry(QRect(690, 530, 111, 41))
        self.Buttontwo_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Textone_label = QLabel(self.centralwidget)
        self.Textone_label.setObjectName(u"Textone_label")
        self.Textone_label.setGeometry(QRect(260, 580, 61, 41))
        self.Textone_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Textone_input = QTextEdit(self.centralwidget)
        self.Textone_input.setObjectName(u"Textone_input")
        self.Textone_input.setGeometry(QRect(330, 580, 271, 41))
        self.Texttwo_label = QLabel(self.centralwidget)
        self.Texttwo_label.setObjectName(u"Texttwo_label")
        self.Texttwo_label.setGeometry(QRect(630, 580, 61, 41))
        self.Texttwo_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Texttwo_input = QTextEdit(self.centralwidget)
        self.Texttwo_input.setObjectName(u"Texttwo_input")
        self.Texttwo_input.setGeometry(QRect(700, 580, 271, 41))
        self.Urlone_input = QTextEdit(self.centralwidget)
        self.Urlone_input.setObjectName(u"Urlone_input")
        self.Urlone_input.setGeometry(QRect(330, 630, 271, 41))
        self.Urltwo_input = QTextEdit(self.centralwidget)
        self.Urltwo_input.setObjectName(u"Urltwo_input")
        self.Urltwo_input.setGeometry(QRect(700, 630, 271, 41))
        self.Urltwo_label = QLabel(self.centralwidget)
        self.Urltwo_label.setObjectName(u"Urltwo_label")
        self.Urltwo_label.setGeometry(QRect(630, 630, 61, 41))
        self.Urltwo_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Urlone_label = QLabel(self.centralwidget)
        self.Urlone_label.setObjectName(u"Urlone_label")
        self.Urlone_label.setGeometry(QRect(260, 630, 61, 41))
        self.Urlone_label.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Updatepresence_button = QPushButton(self.centralwidget)
        self.Updatepresence_button.setObjectName(u"Updatepresence_button")
        self.Updatepresence_button.setGeometry(QRect(530, 700, 241, 41))
        self.Updatepresence_button.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Timestamp = QGroupBox(self.centralwidget)
        self.Timestamp.setObjectName(u"Timestamp")
        self.Timestamp.setGeometry(QRect(340, 220, 501, 131))
        self.None_checkbox = QRadioButton(self.Timestamp)
        self.None_checkbox.setObjectName(u"None_checkbox")
        self.None_checkbox.setGeometry(QRect(10, 30, 101, 31))
        self.None_checkbox.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.Started_checkbox = QRadioButton(self.Timestamp)
        self.Started_checkbox.setObjectName(u"Started_checkbox")
        self.Started_checkbox.setGeometry(QRect(10, 60, 331, 31))
        self.Started_checkbox.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.local_checkbox = QRadioButton(self.Timestamp)
        self.local_checkbox.setObjectName(u"local_checkbox")
        self.local_checkbox.setGeometry(QRect(10, 90, 211, 31))
        self.local_checkbox.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1249, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.ID_label.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.ConnectButton.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.DisconnectButton.setText(QCoreApplication.translate("MainWindow", u"Disconnect", None))
        self.Details_label.setText(QCoreApplication.translate("MainWindow", u"Details", None))
        self.State_label.setText(QCoreApplication.translate("MainWindow", u"State", None))
        self.Timestamp_label.setText(QCoreApplication.translate("MainWindow", u"Timetamp", None))
        self.Largeimage_label.setText(QCoreApplication.translate("MainWindow", u"Large Image", None))
        self.Smallimage_label.setText(QCoreApplication.translate("MainWindow", u"Small Image", None))
        self.Keylarge_label.setText(QCoreApplication.translate("MainWindow", u"Key", None))
        self.Keysmall_label.setText(QCoreApplication.translate("MainWindow", u"Key", None))
        self.Textlarge_label.setText(QCoreApplication.translate("MainWindow", u"Text", None))
        self.Textsmall_label.setText(QCoreApplication.translate("MainWindow", u"Text", None))
        self.Buttonone_label.setText(QCoreApplication.translate("MainWindow", u"Button 1", None))
        self.Buttontwo_label.setText(QCoreApplication.translate("MainWindow", u"Button 2", None))
        self.Textone_label.setText(QCoreApplication.translate("MainWindow", u"Text", None))
        self.Texttwo_label.setText(QCoreApplication.translate("MainWindow", u"Text", None))
        self.Urltwo_label.setText(QCoreApplication.translate("MainWindow", u"Url", None))
        self.Urlone_label.setText(QCoreApplication.translate("MainWindow", u"Url", None))
        self.Updatepresence_button.setText(QCoreApplication.translate("MainWindow", u"Update Presence", None))
        self.Timestamp.setTitle(QCoreApplication.translate("MainWindow", u"GroupBox", None))
        self.None_checkbox.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.Started_checkbox.setText(QCoreApplication.translate("MainWindow", u"Since custom RP started", None))
        self.local_checkbox.setText(QCoreApplication.translate("MainWindow", u"Your local time", None))
    # retranslateUi

